### ISSUE TITLE
Data Analysis/Create Documentation of Data Sources and Data Handling

### ISSUE THREAD

**Issue by MrBrown95** [nikderoso/TIT#3]

**Comment by Rethox** [comment]
Global Surface Summary of the Day is derived from The Integrated Surface Hourly (ISH) dataset. The ISH dataset includes global data obtained from the USAF Climatology Center, located in the Federal Climate Complex with NCDC. The latest daily summary data are normally available 1-2 days after the date-time of the observations used in the daily summaries. The online data files begin with 1929 and are at the time of this writing at the Version 8 software level. Over 9000 stations' data are typically available. The daily elements included in the dataset (as available from each station) are: Mean temperature (.1 Fahrenheit) Mean dew point (.1 Fahrenheit) Mean sea level pressure (.1 mb) Mean station pressure (.1 mb) Mean visibility (.1 miles) Mean wind speed (.1 knots) Maximum sustained wind speed (.1 knots) Maximum wind gust (.1 knots) Maximum temperature (.1 Fahrenheit) Minimum temperature (.1 Fahrenheit) Precipitation amount (.01 inches) Snow depth (.1 inches) Indicator for occurrence of: Fog, Rain or Drizzle, Snow or Ice Pellets, Hail, Thunder, Tornado/Funnel Cloud Global summary of day data for 18 surface meteorological elements are derived from the synoptic/hourly observations contained in USAF DATSAV3 Surface data and Federal Climate Complex Integrated Surface Hourly (ISH). Historical data are generally available for 1929 to the present, with data from 1973 to the present being the most complete. For some periods, one or more countries' data may not be available due to data restrictions or communications problems. In deriving the summary of day data, a minimum of 4 observations for the day must be present (allows for stations which report 4 synoptic observations/day). Since the data are converted to constant units (e.g, knots), slight rounding error from the originally reported values may occur (e.g, 9.9 instead of 10.0). The mean daily values described below are based on the hours of operation for the station. For some stations/countries, the visibility will sometimes 'cluster' around a value (such as 10 miles) due to the practice of not reporting visibilities greater than certain distances. The daily extremes and totals--maximum wind gust, precipitation amount, and snow depth--will only appear if the station reports the data sufficiently to provide a valid value. Therefore, these three elements will appear less frequently than other values. Also, these elements are derived from the stations' reports during the day, and may comprise a 24-hour period which includes a portion of the previous day. The data are reported and summarized based on Greenwich Mean Time (GMT, 0000Z - 2359Z) since the original synoptic/hourly data are reported and based on GMT.
        purpose:  Global summary of the day is comprised of a dozen daily averages computed from global hourly station data. Daily weather elements include mean values of: temperature, dew point temperature, sea level pressure, station pressure, visibility, and wind speed plus maximum and minimum temperature, maximum sustained wind speed and maximum gust, precipitation amount, snow depth, and weather indicators. With the exception of U.S. stations, 24-hour periods are based upon UTC times. Values are usually delayed 24-48 hours from the time of observation.

**Comment by Rethox** [comment]
Zusammenfassung: Mean (Durchschnitts) Werte bestehen aus den über den gesamten betribszeitraum der Station des angegebenen Datensatzes. Max und Min sind die Hösten/Niedrigsten Werte die in diesem zeitraum gemessen wurden. Daten existieren nur wenn sie im messzeitraum vorhanden waren, ergo ohne Regen gibt es im Datensatz keine Niederschlags angabe. Die daten wurden in Konstante einheiten konvertiert, dadurch kann es leichte rundungs abweichungen geben. Es besteht die möglichkeit das daten sich um einen bestimten wert "Clustern" wie bei sichtweite, da sie nur biz zu einer bestimten distanz meldet.

**Comment by Rethox** [comment]
Daten bedeutungen:
TEMP   -> Temperatur in Fahrenheit (Durchschnitt)
DEWP  -> Stationsdruck in millibar (Durchschnitt)
SLP      -> Meeresspiegeldruck in millibar (Durchschnitt)
VISIB    -> Sichtweite in Meilen (Durchschnitt)
WDSP   -> Windgeschwindigkeit in Knoten (Durchschnitt)
MXSPD -> Maximale andauernde Windgeschwindigkeit
GUST    -> Stärkste Windböhe in Knoten
MAX     -> höhste erreichte Temperatur in Fahrenheit
MIN      -> Niedrigste erreichte Temperatur in Fahrenheit
PRCP    -> Niederschlag in 0,01 Inches (0,01 Zoll)
SNDP    -> Schneetiefe in 0,1 Inches (0,1 Zoll)

**Comment by bjarnet** [comment]
Soure of Meteostat-RAW-data? (Synop/Metar)?

**Comment by bjarnet** [comment]
Finished so far, need to implement thi sinto the full documentation
